USE sakila;

-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- 1.  List the number of films per category.

SELECT c.category_id AS Category, COUNT(f.film_id) AS Number_of_films
FROM film AS f
JOIN film_category AS c
ON f.film_id = c.film_id
GROUP BY c.category_id;

-- 2.  Retrieve the store ID, city, and country for each store.

SELECT s.store_id AS Store, ci.city AS City, co.country AS Country
FROM store AS s
JOIN address AS a
ON s.address_id = a.address_id
JOIN city AS ci
ON a.city_id = ci.city_id
JOIN country AS co
ON ci.country_id = co.country_id;

-- 3.  Calculate the total revenue generated by each store in dollars.

SELECT s.store_id AS Store, sum(p.amount) AS Revenue
FROM store as s
JOIN staff as st
ON s.manager_staff_id = st.staff_id
JOIN payment AS p
ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- 4.  Determine the average running time of films for each category.

SELECT c.category_id AS Category, AVG(f.length) AS Average_running_time
FROM film AS f
JOIN film_category AS c
ON f.film_id = c.film_id
GROUP BY c.category_id;

-- 5.  Identify the film categories with the longest average running time.

SELECT c.category_id AS Category, AVG(f.length) AS Average_running_time
FROM film AS f
JOIN film_category AS c
ON f.film_id = c.film_id
GROUP BY c.category_id
ORDER BY Average_running_time DESC;

-- 6.  Display the top 10 most frequently rented movies in descending order.

SELECT f.title AS title, COUNT(r.rental_id) AS number_of_rents
FROM film AS f
JOIN inventory AS i
ON f.film_id = i.film_id
JOIN rental AS r
ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY number_of_rents DESC
LIMIT 10;

-- 7.  Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title, i.store_id, i.inventory_id,
CASE 
	WHEN r.rental_id IS NULL OR r.return_date IS NOT NULL THEN 'Available'
	ELSE 'rented'
END AS status
FROM film AS f
JOIN inventory AS i 
ON f.film_id = i.film_id
LEFT JOIN rental AS r 
ON i.inventory_id = r.inventory_id 
AND r.return_date IS NULL
WHERE f.title = 'Academy Dinosaur' 
AND i.store_id = 1;

-- 8.  Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a `CASE` statement combined with `IFNULL`."

SELECT DISTINCT f.title,
CASE 
	WHEN IFNULL(i.inventory_id, 0) != 0 THEN 'Available'
	ELSE 'NOT available'
END AS availability_status
FROM film AS f
LEFT JOIN inventory AS i 
ON f.film_id = i.film_id
ORDER BY f.title;